
import Head from 'next/head'

import React from 'react';
import Hero from "@/components/Hero";
import About from '@/components/About';
import Experience from '@/components/Experience';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';
import Header from '@/components/Header';
import { Social, PageInfo, Skill,  Project } from "../typings";
import { fetchPageInfo } from "../libs/fetchPageInfo";
import { fetchSkills } from "../libs/fetchSkills";
import { fetchProjects } from "../libs/fetchProjects";
import { fetchSocial } from "../libs/fetchSocials";
import { GetStaticProps,GetServerSideProps } from 'next';



type Props = {
  pageInfo: PageInfo;
  socials: Social[];
  skills: Skill[];
  projects: Project[];
};




const Home =({pageInfo,socials,skills,projects}: Props) => {



  return (
    <div className='h-screen  touch-pan-y overflow-x-hidden snap-y snap-mandatory overflow-y-scroll bg-black'>
      <Head>
        <title>{pageInfo?.name} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      
      <Header socials={socials}  />
      

     <section className='snap-center'>
        <Hero pageInfo={pageInfo} />
         
     </section>
     
     <section id='About' className='snap-center'>
       <About pageInfo={pageInfo} />
     </section>
     
     <section id="Experience" className='snap-center'>
     <Experience skills={skills} />
      </section>

      <section id="Projects" className='snap-center '>
        <Projects projects={projects} />
      </section>
      <section id="Contact" className='snap-end'>
        <Contact />
      </section>

    </div>
  )
  }


export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocial();
  return {
    props: {
      pageInfo,
      socials,
      skills,
      projects,
    },
    //nextjs will regenerate the page every 10 second when a request comes in,
    revalidate: 10,
  };

}
